# Generated by Django 2.1 on 2018-08-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=200)),
                ('store', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('discount', models.CharField(default='N/A', max_length=5)),
                ('link', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date reported')),
            ],
        ),
    ]
