# Generated by Django 2.1 on 2018-08-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_deals', '0003_auto_20180816_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='id',
        ),
        migrations.AlterField(
            model_name='deal',
            name='cover_hash',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
