# Generated by Django 2.1 on 2018-08-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_deals', '0004_auto_20180817_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='id',
            field=models.AutoField(auto_created=True, default='N/A', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='cover_hash',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deal',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
